
export const CHANGE_SENT_STATUS = "CHANGE_SENT_STATUS";
export const SERVICE_CONNECTED = "SERVICE_CONNECTED";
export const CURRENT_IMAGE_ID = "CURRENT_IMAGE_ID";
export const FORM_UPDATE = "FORM_UPDATE";
export const FORM_RESET = "FORM_RESET";
export const UPDATE_SERVICES = "UPDATE_SERVICES";